name: CI Frontend

on:
  push:
    branches:
      - 'main' 
    paths:
      - 'front-end/**' 
  pull_request:
    paths: 
      - 'front-end/**'
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Angular
        working-directory: front-end
        run: npm install
        
      - name: Package
        working-directory: front-end
        run: npm run build --prod
        
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli
      - name: Deploy
        working-directory: front-end/dist/sgcmapp
        run: railway up --detach --service front-app
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        