name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12]

    steps:
     - name: Checkout
       uses: actions/checkout@v1


    - name: install and build
      working-directory: ./integracao-continua
      run: npm install && npm run build

    - name: Deploy
      uses: 
      with:
        branch: gh-pages
        folder: integracao-continua/dist

